config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true

  def deadline?
    deadline <= Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.order(:deadline, :done, :content)
    @new_task = Task.new
    @show_done = false
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.js
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.js
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task)
        .permit(:content, :deadline, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_tr(task)
    classes = task.done ? 'table-success task-done' : ''
    classes = classes + ' task-deadline' if task.deadline?

    content_tag :tr, id: "task-#{task.id}", class: classes do
      yield
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, id: 'task-form') do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.date_field :deadline, value: task.deadline || Date.today, class: 'form-control col-2' %>
    <%= form.text_field :content, class: 'form-control', placeholder: 'Write down your TODO here'  %>
    <div class="actions input-group-append">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script>
  $('#task_content').focus();
</script>

app/views/tasks/_task.html.erb
<%= task_tr(task) do %>
  <td>
    <%= check_box :task, :done, { id: "done-checkbox-#{task.id}", class: 'done-checkbox', checked: task.done }, "true", "false" %>
  </td>
  <td class="deadline">
    <%= task.deadline %>
  </td>
  <td class="content">
    <%= task.content %>
  </td>
  <td>
    <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-warning' %>
    <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </td>
<% end %>

<script>
  $("#done-checkbox-<%= task.id %>").change(function() {
    return ajaxUpdateDone(<%= task.id %>, $(this).prop("checked"));
  });

  // trigger checkbox on td clicked.
  $("td:has(#done-checkbox-<%= task.id %>)").click(function() {
    $(this).children('.done-checkbox').trigger('click');
  });

  // Stop propagation.
  $("#done-checkbox-<%= task.id %>").click(function(event) {
    event.stopPropagation();
  });

  if (typeof ajaxUpdateDone != 'function') {
    function ajaxUpdateDone(id, done) {
      console.log('ajaxUpdateDone');
      console.log('id = ' + id);
      console.log('done = ' + done);
      $.ajax({
        url: "tasks/" + id,
        data: { task: { done: done } },
        type: "PATCH",
        dataType: 'json'
      }).then(
        data => {
          if (done) {
              $("#task-" + id).addClass("table-success");
              $("#task-" + id).addClass("task-done");
          } else {
              $("#task-" + id).removeClass("table-success");
              $("#task-" + id).removeClass("task-done");
          }
        },
        error => alert("更新に失敗しました。")
      );
    }
  }
</script>

app/views/tasks/create.js.erb
$('table > tbody').prepend('<%== j render partial: 'task', locals: { task: @task } %>');
$('#task_content').val(''); // clear form

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card m-2 mx-auto" style="width: 65%">
  <div class="card-header">
    <h3>TODO List</h3>
  </div>

  <div class="card-body">
    <%= render 'form', task: @new_task %>

    <div class="custom-control custom-switch">
      <%= check_box_tag :show_done, true, @show_done, class: "custom-control-input" %>
      <%= label_tag :show_done, 'Show done', class: "custom-control-label" %>
    </div>

    <div class="table-responsive">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th class="th-sm" style="width: 7%"><%= label :task, :done %></th>
            <th class="th-sm" style="width: 16%"><%= label :task, :deadline %></th>
            <th class="th-sm"><%= label :task, :content %></th>
            <th class="th-sm" style="width: 15%">action</th>
          </tr>
        </thead>

        <tbody>
          <%= render @tasks %>
        </tbody>
      </table>
    </div>

    <br>
  </div>
</div>

<script>
  function toggleShowDone() {
    if ($('#show_done').prop("checked")) {
      $('tr.task-done').show();
    } else {
      $('tr.task-done').hide();
    }
  };

  $('#show_done').change(toggleShowDone);

  toggleShowDone();
</script>

<style>
tr.task-done > td.deadline, tr.task-done > td.content {
  text-decoration: line-through;
}
tr.task-deadline > td.deadline, tr.task-deadline > td.content {
  color: red;
  font-weight: bold;
}
</style>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>